services:
  backend:
    image: meditation-backend
    container_name: meditation-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"

  frontend:
    image: meditation-frontend
    container_name: meditation-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://meditation-backend:5000
    depends_on:
      - backend